
-- Dropping Schemas (connect to jd_db DB first)
DROP SCHEMA IF EXISTS bronze CASCADE;
DROP SCHEMA IF EXISTS silver CASCADE;
DROP SCHEMA IF EXISTS gold CASCADE;


DROP SCHEMA IF EXISTS metadata CASCADE;
