-- bronze
CREATE TABLE incidents.bronze.br_fire_incidents (
    incident_number TEXT,
    exposure_number TEXT,
    id TEXT,
    address TEXT,
    incident_date TEXT,
    call_number TEXT,
    alarm_dttm TEXT,
    arrival_dttm TEXT,
    close_dttm TEXT,
    city TEXT,
    zipcode TEXT,
    battalion TEXT,
    station_area TEXT,
    box TEXT,
    suppression_units TEXT,
    suppression_personnel TEXT,
    ems_units TEXT,
    ems_personnel TEXT,
    other_units TEXT,
    other_personnel TEXT,
    first_unit_on_scene TEXT,
    estimated_property_loss TEXT,
    estimated_contents_loss TEXT,
    fire_fatalities TEXT,
    fire_injuries TEXT,
    civilian_fatalities TEXT,
    civilian_injuries TEXT,
    number_of_alarms TEXT,
    primary_situation TEXT,
    mutual_aid TEXT,
    action_taken_primary TEXT,
    action_taken_secondary TEXT,
    action_taken_other TEXT,
    detector_alerted_occupants TEXT,
    property_use TEXT,
    area_of_fire_origin TEXT,
    ignition_cause TEXT,
    ignition_factor_primary TEXT,
    ignition_factor_secondary TEXT,
    heat_source TEXT,
    item_first_ignited TEXT,
    human_factors_associated_with_ignition TEXT,
    structure_type TEXT,
    structure_status TEXT,
    floor_of_fire_origin TEXT,
    fire_spread TEXT,
    no_flame_spread TEXT,
    num_floors_min_damage TEXT,
    num_floors_significant_damage TEXT,
    num_floors_heavy_damage TEXT,
    num_floors_extreme_damage TEXT,
    detectors_present TEXT,
    detector_type TEXT,
    detector_operation TEXT,
    detector_effectiveness TEXT,
    detector_failure_reason TEXT,
    automatic_extinguishing_system_present TEXT,
    automatic_extinguishing_system_type TEXT,
    automatic_extinguishing_system_performance TEXT,
    automatic_extinguishing_system_failure_reason TEXT,
    num_sprinkler_heads_operating TEXT,
    supervisor_district TEXT,
    neighborhood_district TEXT,
    point TEXT, 
    data_as_of TEXT,
    data_loaded_at TEXT,
    insert_timestamp TIMESTAMP DEFAULT NOW()
);


-- silver
CREATE TABLE incidents.silver.sl_fire_incidents (
    fire_incident_id TEXT,
    incident_number VARCHAR(8),
    exposure_number INT,
    address TEXT,
    incident_date TIMESTAMP,
    date_id INT,
    call_number TEXT,
    alarm_dttm TIMESTAMP,
    arrival_dttm TIMESTAMP,
    close_dttm TIMESTAMP,
    city TEXT,
    zipcode TEXT,
    battalion TEXT,
    station_area TEXT,
    box TEXT,
    suppression_units INT,
    suppression_personnel INT,
    ems_units INT,
    ems_personnel INT,
    other_units INT,
    other_personnel INT,
    first_unit_on_scene TEXT,
    estimated_property_loss NUMERIC(15,2),
    estimated_contents_loss NUMERIC(15,2),
    fire_fatalities INT,
    fire_injuries INT,
    civilian_fatalities INT,
    civilian_injuries INT,
    number_of_alarms INT,
    primary_situation TEXT,
    mutual_aid TEXT,
    action_taken_primary TEXT,
    action_taken_secondary TEXT,
    action_taken_other TEXT,
    detector_alerted_occupants TEXT,
    property_use TEXT,
    area_of_fire_origin TEXT,
    ignition_cause TEXT,
    ignition_factor_primary TEXT,
    ignition_factor_secondary TEXT,
    heat_source TEXT,
    item_first_ignited TEXT,
    human_factors_associated_with_ignition TEXT,
    structure_type TEXT,
    structure_status TEXT,
    floor_of_fire_origin INT,
    fire_spread TEXT,
    no_flame_spread TEXT,
    num_floors_min_damage INT,
    num_floors_significant_damage INT,
    num_floors_heavy_damage INT,
    num_floors_extreme_damage INT,
    detectors_present TEXT,
    detector_type TEXT,
    detector_operation TEXT,
    detector_effectiveness TEXT,
    detector_failure_reason TEXT,
    automatic_extinguishing_system_present TEXT,
    automatic_extinguishing_system_type TEXT,
    automatic_extinguishing_system_performance TEXT,
    automatic_extinguishing_system_failure_reason TEXT,
    num_sprinkler_heads_operating INT,
    supervisor_district TEXT,
    neighborhood_district TEXT,
    point GEOMETRY(POINT, 4326), 
    data_as_of TIMESTAMP,
    data_loaded_at TIMESTAMP,
    insert_timestamp TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (incident_number, exposure_number)
);


-- gold
CREATE TABLE incidents.gold.dim_date(
    date_id INT PRIMARY KEY,
    full_date DATE,
    year INT,
    quarter INT,
    month INT,
    month_name VARCHAR(10),
    week_of_year INT,
    day_of_week INT,
    day_name VARCHAR(10),
    is_weekend BOOLEAN,
    insert_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE incidents.gold.fact_fire_incidents (
    fire_incident_id TEXT, 
    incident_number VARCHAR(8),
    exposure_number INT,
    address TEXT,
    incident_date TIMESTAMP,
    date_id INT,
    call_number TEXT,
    alarm_dttm TIMESTAMP,
    arrival_dttm TIMESTAMP,
    close_dttm TIMESTAMP,
    city TEXT,
    zipcode TEXT,
    battalion TEXT,
    station_area TEXT,
    box TEXT,
    suppression_units INT,
    suppression_personnel INT,
    ems_units INT,
    ems_personnel INT,
    other_units INT,
    other_personnel INT,
    first_unit_on_scene TEXT,
    estimated_property_loss NUMERIC(15,2),
    estimated_contents_loss NUMERIC(15,2),
    fire_fatalities INT,
    fire_injuries INT,
    civilian_fatalities INT,
    civilian_injuries INT,
    number_of_alarms INT,
    primary_situation TEXT,
    mutual_aid TEXT,
    action_taken_primary TEXT,
    action_taken_secondary TEXT,
    action_taken_other TEXT,
    detector_alerted_occupants TEXT,
    property_use TEXT,
    area_of_fire_origin TEXT,
    ignition_cause TEXT,
    ignition_factor_primary TEXT,
    ignition_factor_secondary TEXT,
    heat_source TEXT,
    item_first_ignited TEXT,
    human_factors_associated_with_ignition TEXT,
    structure_type TEXT,
    structure_status TEXT,
    floor_of_fire_origin INT,
    fire_spread TEXT,
    no_flame_spread TEXT,
    num_floors_min_damage INT,
    num_floors_significant_damage INT,
    num_floors_heavy_damage INT,
    num_floors_extreme_damage INT,
    detectors_present TEXT,
    detector_type TEXT,
    detector_operation TEXT,
    detector_effectiveness TEXT,
    detector_failure_reason TEXT,
    automatic_extinguishing_system_present TEXT,
    automatic_extinguishing_system_type TEXT,
    automatic_extinguishing_system_performance TEXT,
    automatic_extinguishing_system_failure_reason TEXT,
    num_sprinkler_heads_operating INT,
    supervisor_district TEXT,
    neighborhood_district TEXT,
    point GEOMETRY(POINT, 4326), 
    data_as_of TIMESTAMP,
    data_loaded_at TIMESTAMP,
    insert_timestamp TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (incident_number, exposure_number),
    FOREIGN KEY (date_id) REFERENCES incidents.gold.dim_date(date_id)
);

--------------------------------
CREATE TABLE IF NOT EXISTS incidents.metadata.load_tracker (
    model_name TEXT PRIMARY KEY,
    last_data_as_of TIMESTAMP,
    prev_data_as_of TIMESTAMP);