WITH load_dates AS (
    SELECT prev_data_as_of
    FROM incidents.metadata.load_tracker
    WHERE model_name = 'fire_incidents'
)
SELECT
    fire_incident_id,
    incident_number,
    exposure_number,
    address,
    incident_date,
    date_id,
    call_number,
    alarm_dttm,
    arrival_dttm,
    close_dttm,
    city,
    zipcode,
    battalion,
    station_area,
    box,
    suppression_units,
    suppression_personnel,
    ems_units,
    ems_personnel,
    other_units,
    other_personnel,
    first_unit_on_scene,
    estimated_property_loss,
    estimated_contents_loss,
    fire_fatalities,
    fire_injuries,
    civilian_fatalities,
    civilian_injuries,
    number_of_alarms,
    primary_situation,
    mutual_aid,
    action_taken_primary,
    action_taken_secondary,
    action_taken_other,
    detector_alerted_occupants,
    property_use,
    area_of_fire_origin,
    ignition_cause,
    ignition_factor_primary,
    ignition_factor_secondary,
    heat_source,
    item_first_ignited,
    human_factors_associated_with_ignition,
    structure_type,
    structure_status,
    floor_of_fire_origin,
    fire_spread,
    no_flame_spread,
    num_floors_min_damage,
    num_floors_significant_damage,
    num_floors_heavy_damage,
    num_floors_extreme_damage,
    detectors_present,
    detector_type,
    detector_operation,
    detector_effectiveness,
    detector_failure_reason,
    automatic_extinguishing_system_present,
    automatic_extinguishing_system_type,
    automatic_extinguishing_system_performance,
    automatic_extinguishing_system_failure_reason,
    num_sprinkler_heads_operating,
    supervisor_district,
    neighborhood_district,
    point,
    data_as_of,
    data_loaded_at,
    CURRENT_TIMESTAMP AS insert_timestamp       
FROM {{ ref('sl_fire_incidents') }}, load_dates
where (data_as_of>prev_data_as_of and  prev_data_as_of is not NULL) 
or  (prev_data_as_of is NULL)

